---
version: '2.1'
services:

  proxy:
    image: zicklam/squid:latest
    container_name: squid
    mem_limit: 512M
    ports: 
      - "3128:3128"
    restart: always 
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
