---
version: '3.6'
services:

  proxy:
    image: zicklam/squid:latest
    container_name: squid
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
    ports: 
      - "3128:3128"
    restart: always 
    environment:
      - HOSTNAME=demosys
